POST http://localhost:4000/app/form
Content-Type: application/json

{
    "chekinDate":"10/06/21",
    "chekoutDate":"12/06/21",
    "adult":"2",
    "children":"1",
    "type":"Cabane O Perchée",
    "firstName":"Roberta",
    "email":"john@Wayne.fr",
    "tel":"222222",
    "message":"Rajoutez un lit double s'il vous plait"

}
